#!/bin/bash

set -e

aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 896720489482.dkr.ecr.ap-southeast-2.amazonaws.com

cd /home/ebpearls/stage
docker-compose pull ebt_web_stage
docker-compose rm -s -f ebt_web_stage
docker-compose up -d ebt_web_stage
docker system prune -f

